using System;
using System.Collections.Generic;
using System.Linq;
using TagTool.Cache;
using TagTool.Commands.Common;
using TagTool.Common;
using TagTool.Tags.Definitions;
using static TagTool.Tags.Definitions.MultiplayerGlobals.MultiplayerUniversalBlock;

namespace TagTool.Commands.Modding
{
    public class SetCustomizationFromModelCommand : Command
    {
        private GameCache CacheContext { get; }

        public SetCustomizationFromModelCommand(GameCache cacheContext)
            : base(false,
                   "SetCustomizationFromModel",
                   "Sets a customization block in a multiplayer_globals tag to mirror regions and permutations from a model tag. " +
                   "Clears the existing customization block first. For each permutation, its description is generated by appending " +
                   "'_description' to its original string (using the StringTable), and a variant block is created containing the region " +
                   "and permutation. If the customization index is -1, a new customization block is created and the user is prompted to " +
                   "enter a name for it.",
                   "SetCustomizationFromModel [mulg_tag_path] [customization_index] [model_tag_path] [variant_index (optional)]",
                   "Sets a customization block in a multiplayer_globals tag to mirror regions and permutations from a model tag. " +
                   "Clears the existing customization block first. For each permutation, its description is generated by appending " +
                   "'_description' to its original string (using the StringTable), and a variant block is created containing the region " +
                   "and permutation. If the customization index is -1, a new customization block is created and the user is prompted to " +
                   "enter a name for it.")
        {
            CacheContext = cacheContext;
        }

        public override object Execute(List<string> args)
        {
            // Validate arguments.
            if (args.Count < 3)
            {
                Console.WriteLine("Usage: SetCustomizationFromModel [mulg_tag_path] [customization_index] [model_tag_path] [variant_index (optional)]");
                return false;
            }

            // The virtual tag path for the multiplayer_globals tag.
            string mulgPath = args[0];

            if (!int.TryParse(args[1], out int customizationIndex))
            {
                Console.WriteLine("Invalid customization index.");
                return false;
            }

            // The virtual tag path for the model tag.
            string modelPath = args[2];

            int variantIndex = -1;
            if (args.Count >= 4)
            {
                if (!int.TryParse(args[3], out variantIndex))
                {
                    Console.WriteLine("Invalid variant index.");
                    return false;
                }
            }

            // Retrieve the CachedTag for the multiplayer_globals tag from the cache context.
            if (!CacheContext.TagCache.TryGetCachedTag(mulgPath, out CachedTag mulgTagDefinition))
            {
                Console.WriteLine($"Could not find tag: {mulgPath}");
                return false;
            }

            MultiplayerGlobals mulgTagInstance;
            try
            {
                using (var stream = CacheContext.OpenCacheRead())
                {
                    // Deserialize using the tag cache entry.
                    mulgTagInstance = CacheContext.Deserialize<MultiplayerGlobals>(stream, mulgTagDefinition);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error reading mulg tag: {ex.Message}");
                return false;
            }

            // Retrieve the CachedTag for the model tag.
            if (!CacheContext.TagCache.TryGetCachedTag(modelPath, out CachedTag modelTagDefinition))
            {
                Console.WriteLine($"Could not find tag: {modelPath}");
                return false;
            }

            Model modelTagInstance;
            try
            {
                using (var stream = CacheContext.OpenCacheRead())
                {
                    modelTagInstance = CacheContext.Deserialize<Model>(stream, modelTagDefinition);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error reading model tag: {ex.Message}");
                return false;
            }

            if (modelTagInstance == null || (variantIndex != -1 && (modelTagInstance.Variants == null || modelTagInstance.Variants.Count == 0)))
            {
                Console.WriteLine("Model or its variants not found.");
                return false;
            }

            // Choose the model variant or use collision regions if no variant is specified.
            var regionsToUse = variantIndex == -1
                ? modelTagInstance.CollisionRegions.Cast<object>().ToList()
                : modelTagInstance.Variants[variantIndex].Regions.Cast<object>().ToList();

            // Retrieve the customization list.
            var customizationList = mulgTagInstance.Universal?[0]?.CustomizableCharacters;
            if (customizationList == null)
            {
                Console.WriteLine("Customizable characters not found in multiplayer_globals.");
                return false;
            }

            CustomizedModelCharacter customization;
            if (customizationIndex == -1)
            {
                // Create a new customization block.
                customization = new CustomizedModelCharacter
                {
                    CharacterName = GetOrAddStringFromUser("Enter the character name for the new customization block: "),
                    Regions = new List<CustomizedModelCharacter.Region>()
                };
                customizationList.Add(customization);
                customizationIndex = customizationList.Count - 1;
            }
            else
            {
                if (customizationIndex < 0 || customizationIndex >= customizationList.Count)
                {
                    Console.WriteLine("Invalid customization index for multiplayer_globals.");
                    return false;
                }
                customization = customizationList[customizationIndex];
            }

            // Clear the existing regions and permutations in the customization block.
            customization.Regions.Clear();

            // Build a lookup of existing regions (by their StringId).
            Dictionary<StringId, CustomizedModelCharacter.Region> existingRegions = new Dictionary<StringId, CustomizedModelCharacter.Region>();
            foreach (var region in customization.Regions)
            {
                if (region.Name != StringId.Invalid)
                    existingRegions[region.Name] = region;
            }

            // Process each region from the model variant or collision regions.
            foreach (object region in regionsToUse)
            {
                dynamic modelRegion = region;
                if (modelRegion.Name == StringId.Invalid)
                    continue;

                CustomizedModelCharacter.Region customRegion;
                if (!existingRegions.TryGetValue(modelRegion.Name, out customRegion))
                {
                    customRegion = new CustomizedModelCharacter.Region
                    {
                        Name = modelRegion.Name,
                        Permutations = new List<CustomizedModelCharacter.Region.Permutation>()
                    };
                    customization.Regions.Add(customRegion);
                }

                // Process permutations from the model region.
                var validModelPermutations = ((IEnumerable<dynamic>)modelRegion.Permutations)
                    .Where(p => p.Name != StringId.Invalid)
                    .ToList();

                int targetPermCount = validModelPermutations.Count;

                if (customRegion.Permutations == null)
                    customRegion.Permutations = new List<CustomizedModelCharacter.Region.Permutation>();

                // Remove any invalid permutation entries.
                customRegion.Permutations.RemoveAll(p => p.Name == StringId.Invalid);

                // Adjust the count of permutations to match the model.
                while (customRegion.Permutations.Count < targetPermCount)
                {
                    var newModelPerm = validModelPermutations[customRegion.Permutations.Count];
                    var newPerm = new CustomizedModelCharacter.Region.Permutation
                    {
                        Name = newModelPerm.Name,
                        Description = CacheContext.StringTable.GetOrAddString(
                                          CacheContext.StringTable.GetString(newModelPerm.Name) + "_description"),
                        Variant = new List<CustomizedModelCharacter.Region.Permutation.VariantBlock>()
                    };
                    customRegion.Permutations.Add(newPerm);
                }
                while (customRegion.Permutations.Count > targetPermCount)
                {
                    customRegion.Permutations.RemoveAt(customRegion.Permutations.Count - 1);
                }

                // Update each permutation.
                for (int i = 0; i < targetPermCount; i++)
                {
                    var modelPerm = validModelPermutations[i];
                    var customPerm = customRegion.Permutations[i];

                    customPerm.Name = modelPerm.Name;
                    customPerm.Description = CacheContext.StringTable.GetOrAddString(
                        CacheContext.StringTable.GetString(modelPerm.Name) + "_description");

                    // Create or clear the variant block list.
                    if (customPerm.Variant == null)
                        customPerm.Variant = new List<CustomizedModelCharacter.Region.Permutation.VariantBlock>();
                    else
                        customPerm.Variant.Clear();

                    var newVariantBlock = new CustomizedModelCharacter.Region.Permutation.VariantBlock
                    {
                        Region = customRegion.Name,
                        Permutation = customPerm.Name
                    };

                    customPerm.Variant.Add(newVariantBlock);
                }
            }

            // Write the updated multiplayer_globals tag back into the cache.
            try
            {
                using (var stream = CacheContext.OpenCacheReadWrite())
                {
                    CacheContext.Serialize(stream, mulgTagDefinition, mulgTagInstance);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error writing updated mulg tag: {ex.Message}");
                return false;
            }

            Console.WriteLine("Customization updated from model successfully.");
            return true;
        }

        private StringId GetOrAddStringFromUser(string message)
        {
            Console.WriteLine(message);
            string value = Console.ReadLine().Trim();

            if (value == "\n" || value == "skip")
                return StringId.Invalid;

            return CacheContext.StringTable.GetOrAddString(value);
        }
    }
}