namespace TagTool.Ai
{
    public enum ActorTypeEnum : short
    {
        Elite,
        Jackal,
        Grunt,
        Hunter,
        Engineer,
        Assassin,
        Player,
        Marine,
        Crew,
        CombatForm,
        InfectionForm,
        CarrierForm,
        Monitor,
        Sentinel,
        None,
        MountedWeapon,
        Brute,
        Prophet,
        Bugger,
        Juggernaut,
        PureFormStealth,
        PureFormTank,
        PureFormRanged,
        Scarab,
        Guardian
    }

    public enum ActorTypeEnumReach : short
    {
        None,
        Player,
        Marine,
        Crew,
        Spartan,
        Elite,
        Jackal,
        Grunt,
        Brute,
        Hunter,
        Prophet,
        Bugger,
        Scarab,
        Engineer,
        Skirmisher,
        Mule,
        MountedWeapon
    }
}
