using System.Collections.Generic;
using TagTool.Common;

namespace TagTool.Commands.Zeus
{
    public static class Halo3Ares
    {
        public static string CachePath = @"F:\AresTest\guardian.map";

        public static Dictionary<Tag, string> Halo3AresGroups = new Dictionary<Tag, string>
        {
            { new Tag("$#!+"), "cache_file_sound" },
            { new Tag("*cen"), "scenario_scenery_resource" },
            { new Tag("*eap"), "scenario_weapons_resource" },
            { new Tag("*ehi"), "scenario_vehicles_resource" },
            { new Tag("*fsc"), "scenario_effect_scenery_resource" },
            { new Tag("*igh"), "scenario_lights_resource" },
            { new Tag("*ipd"), "scenario_bipeds_resource" },
            { new Tag("*qip"), "scenario_equipment_resource" },
            { new Tag("*rea"), "scenario_creature_resource" },
            { new Tag("*sce"), "scenario_sound_scenery_resource" },
            { new Tag("/**/"), "scenario_comments_resource" },
            { new Tag("<fx>"), "sound_effect_template" },
            { new Tag("BooM"), "stereo_system" },
            { new Tag("adlg"), "ai_dialogue_globals" },
            { new Tag("ai**"), "scenario_ai_resource" },
            { new Tag("ant!"), "antenna" },
            { new Tag("beam"), "beam_system" },
            { new Tag("bink"), "bink" },
            { new Tag("bipd"), "biped" },
            { new Tag("bitm"), "bitmap" },
            { new Tag("bkey"), "gui_button_key_definition" },
            { new Tag("bloc"), "crate" },
            { new Tag("bmp3"), "gui_bitmap_widget_definition" },
            { new Tag("bsdt"), "breakable_surface" },
            { new Tag("cddf"), "collision_damage" },
            { new Tag("cfxs"), "camera_fx_settings" },
            { new Tag("chad"), "chud_animation_definition" },
            { new Tag("char"), "character" },
            { new Tag("chdt"), "chud_definition" },
            { new Tag("chgd"), "chud_globals_definition" },
            { new Tag("chmt"), "chocolate_mountain_new" },
            { new Tag("cin*"), "scenario_cinematics_resource" },
            { new Tag("cine"), "cinematic" },
            { new Tag("cisc"), "cinematic_scene" },
            { new Tag("clu*"), "scenario_cluster_data_resource" },
            { new Tag("clwd"), "cloth" },
            { new Tag("cmpu"), "compute_shader" },
            { new Tag("cntl"), "contrail_system" },
            { new Tag("coll"), "collision_model" },
            { new Tag("colo"), "color_table" },
            { new Tag("crea"), "creature" },
            { new Tag("crte"), "cortana_effect_definition" },
            { new Tag("ctrl"), "device_control" },
            { new Tag("cub*"), "scenario_cubemap_resource" },
            { new Tag("dc*s"), "scenario_decorators_resource" },
            { new Tag("dctr"), "decorator_set" },
            { new Tag("dec*"), "scenario_decals_resource" },
            { new Tag("decs"), "decal_system" },
            { new Tag("devi"), "device" },
            { new Tag("devo"), "cellular_automata" },
            { new Tag("dgr*"), "scenario_devices_resource" },
            { new Tag("dobc"), "detail_object_collection" },
            { new Tag("draw"), "rasterizer_cache_file_globals" },
            { new Tag("drdf"), "damage_response_definition" },
            { new Tag("dsrc"), "gui_datasource_definition" },
            { new Tag("effe"), "effect" },
            { new Tag("effg"), "effect_globals" },
            { new Tag("efsc"), "effect_scenery" },
            { new Tag("egor"), "screen_effect" },
            { new Tag("eqip"), "equipment" },
            { new Tag("flck"), "flock" },
            { new Tag("fldy"), "fluid_dynamics" },
            { new Tag("fog "), "planar_fog" },
            { new Tag("foot"), "material_effects" },
            { new Tag("fpch"), "patchy_fog" },
            { new Tag("frag"), "fragment" },
            { new Tag("gint"), "giant" },
            { new Tag("glps"), "global_pixel_shader" },
            { new Tag("glvs"), "global_vertex_shader" },
            { new Tag("goof"), "multiplayer_variant_settings_interface_definition" },
            { new Tag("grup"), "gui_group_widget_definition" },
            { new Tag("hlmt"), "model" },
            { new Tag("hlsl"), "hlsl_include" },
            { new Tag("hsc*"), "scenario_hs_source_file" },
            { new Tag("item"), "item" },
            { new Tag("itmc"), "item_collection" },
            { new Tag("jmad"), "model_animation_graph" },
            { new Tag("jmrq"), "sandbox_text_value_pair_definition" },
            { new Tag("jpt!"), "damage_effect" },
            { new Tag("lens"), "lens_flare" },
            { new Tag("ligh"), "light" },
            { new Tag("lsnd"), "sound_looping" },
            { new Tag("lst3"), "gui_list_widget_definition" },
            { new Tag("lswd"), "leaf_system" },
            { new Tag("ltvl"), "light_volume_system" },
            { new Tag("mach"), "device_machine" },
            { new Tag("matg"), "globals" },
            { new Tag("mcsr"), "mouse_cursor_definition" },
            { new Tag("mdl3"), "gui_model_widget_definition" },
            { new Tag("mdlg"), "ai_mission_dialogue" },
            { new Tag("metr"), "meter" },
            { new Tag("mffn"), "muffin" },
            { new Tag("mode"), "render_model" },
            { new Tag("mply"), "multiplayer_scenario_description" },
            { new Tag("mulg"), "multiplayer_globals" },
            { new Tag("nclt"), "new_cinematic_lighting" },
            { new Tag("obje"), "object" },
            { new Tag("perf"), "performance_throttles" },
            { new Tag("phmo"), "physics_model" },
            { new Tag("pixl"), "pixel_shader" },
            { new Tag("play"), "cache_file_resource_layout_table" },
            { new Tag("pmdf"), "particle_model" },
            { new Tag("pmov"), "particle_physics" },
            { new Tag("pphy"), "point_physics" },
            { new Tag("proj"), "projectile" },
            { new Tag("prt3"), "particle" },
            { new Tag("rasg"), "rasterizer_globals" },
            { new Tag("rm  "), "render_method" },
            { new Tag("rmb "), "shader_beam" },
            { new Tag("rmc"), "shader_contrail" },
            { new Tag("rmcs"), "shader_custom" },
            { new Tag("rmct"), "shader_cortana" },
            { new Tag("rmd "), "shader_decal" },
            { new Tag("rmdf"), "render_method_definition" },
            { new Tag("rmfl"), "shader_foliage" },
            { new Tag("rmhg"), "shader_halogram" },
            { new Tag("rmlv"), "shader_light_volume" },
            { new Tag("rmop"), "render_method_option" },
            { new Tag("rmp"), "shader_particle" },
            { new Tag("rmsh"), "shader" },
            { new Tag("rmsk"), "shader_skin" },
            { new Tag("rmt2"), "render_method_template" },
            { new Tag("rmtr"), "shader_terrain" },
            { new Tag("rmw "), "shader_water" },
            { new Tag("rwrd"), "render_water_ripple" },
            { new Tag("sFdT"), "scenario_faux_data" },
            { new Tag("sLdT"), "scenario_lightmap" },
            { new Tag("sbsp"), "scenario_structure_bsp" },
            { new Tag("scen"), "scenery" },
            { new Tag("scn3"), "gui_screen_widget_definition" },
            { new Tag("scnr"), "scenario" },
            { new Tag("sddt"), "structure_design" },
            { new Tag("sefc"), "area_screen_effect" },
            { new Tag("sfx+"), "sound_effect_collection" },
            { new Tag("sgp!"), "sound_global_propagation" },
            { new Tag("shit"), "shield_impact" },
            { new Tag("sily"), "text_value_pair_definition" },
            { new Tag("skn3"), "gui_skin_definition" },
            { new Tag("sky*"), "scenario_sky_references_resource" },
            { new Tag("skya"), "sky_atm_parameters" },
            { new Tag("smap"), "shared_cache_file_layout" },
            { new Tag("sncl"), "sound_classes" },
            { new Tag("snd!"), "sound" },
            { new Tag("snde"), "sound_environment" },
            { new Tag("snmx"), "sound_mix" },
            { new Tag("spk!"), "sound_dialogue_constants" },
            { new Tag("ssce"), "sound_scenery" },
            { new Tag("sslt"), "scenario_structure_lighting_resource" },
            { new Tag("stli"), "scenario_structure_lighting_info" },
            { new Tag("stse"), "structure_seams" },
            { new Tag("styl"), "style" },
            { new Tag("term"), "device_terminal" },
            { new Tag("trak"), "camera_track" },
            { new Tag("trg*"), "scenario_trigger_volumes_resource" },
            { new Tag("txt3"), "gui_text_widget_definition" },
            { new Tag("udlg"), "dialogue" },
            { new Tag("ugh!"), "sound_cache_file_gestalt" },
            { new Tag("uise"), "user_interface_sounds_definition" },
            { new Tag("unic"), "multilingual_unicode_string_list" },
            { new Tag("unit"), "unit" },
            { new Tag("vehc"), "vehicle_collection" },
            { new Tag("vehi"), "vehicle" },
            { new Tag("vtsh"), "vertex_shader" },
            { new Tag("wacd"), "gui_widget_animation_collection_definition" },
            { new Tag("wclr"), "gui_widget_color_animation_definition" },
            { new Tag("weap"), "weapon" },
            { new Tag("wezr"), "game_engine_settings_definition" },
            { new Tag("wfon"), "gui_widget_font_animation_definition" },
            { new Tag("wgan"), "gui_widget_animation_definition" },
            { new Tag("wgtz"), "user_interface_globals_definition" },
            { new Tag("whip"), "cellular_automata2d" },
            { new Tag("wigl"), "user_interface_shared_globals_definition" },
            { new Tag("wind"), "wind" },
            { new Tag("wpos"), "gui_widget_position_animation_definition" },
            { new Tag("wrot"), "gui_widget_rotation_animation_definition" },
            { new Tag("wscl"), "gui_widget_scale_animation_definition" },
            { new Tag("wspr"), "gui_widget_sprite_animation_definition" },
            { new Tag("wtuv"), "gui_widget_texture_coordinate_animation_definition" },
            { new Tag("zone"), "cache_file_resource_gestalt" },
        };
    }
}