namespace TagTool.BlamFile.MCC
{
    public enum GameCategoryIndex 
    {
        GameCategory_NONE = -1,
        GameCategory_CTF = 0,
        GameCategory_Slayer = 1,
        GameCategory_Oddball = 2,
        GameCategory_KOTH = 3,
        GameCategory_Juggernaut = 4,
        GameCategory_Infection = 5,
        GameCategory_Flood = 6,
        GameCategory_Race = 7,
        GameCategory_Extraction = 8,
        GameCategory_Dominion = 9,
        GameCategory_Regicide = 10,
        GameCategory_Grifball = 11,
        GameCategory_Ricochet = 12,
        GameCategory_Sandbox = 13,
        GameCategory_VIP = 14,
        GameCategory_Territories = 15,
        GameCategory_Assault = 16,
        GameCategory_Payback = 17,
        GameCategory_Campaign = 18,
        GameCategory_Playlist = 19,
        GameCategory_Firefight = 20,
        GameCategory_Stockpile = 21,
        GameCategory_Headhunter = 22,
        GameCategory_Invasion = 23,
        GameCategory_ActionSack = 24,
        GameCategory_SpartanOps = 25,
        GameCategory_PreGameWarmUp = 26,
        GameCategory_GunGame = 27,
        GameCategory_Count = 28,
    }
}
