name: TagTool Build

on:
  push:
    branches: [ "dev" ]

jobs:
  build-win:
    env:
      TARGET_FRAMEWORK: net8.0-windows
      PLATFORM: x64

    strategy:
      matrix:
        BUILD_CONFIGURATION: [ Debug, Release ]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Initialize Submodules 
      uses: snickerbockers/submodules-init@v4

    - name: Determine Version
      id: determine_version
      run: |
        $version = (git rev-parse --short=7 HEAD).Trim()
        Write-Output "Version determined: $version"
        Write-Host "::set-output name=version::$version"
          
    - name: Install 7Zip
      run: |
        Invoke-WebRequest -Uri "https://www.7-zip.org/a/7z1900-x64.msi" -OutFile "$env:TEMP\7z.msi"
        Start-Process -Wait -FilePath msiexec -ArgumentList "/i", "$env:TEMP\7z.msi", "/quiet" 

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore Packages
      run: nuget restore TagTool.sln

    - name: Build solution
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: msbuild TagTool.sln /t:rebuild /p:Platform=${{ env.PLATFORM }} /p:Configuration=${{ matrix.BUILD_CONFIGURATION }} /p:TargetFramework=${{ env.TARGET_FRAMEWORK }}

    - name: Zip Release
      run: |
        & "C:\Program Files\7-Zip\7z.exe" a ${{ matrix.BUILD_CONFIGURATION }}_${{ env.PLATFORM }}.7z ./TagTool/bin/${{ env.PLATFORM }}/${{ matrix.BUILD_CONFIGURATION }}/${{ env.TARGET_FRAMEWORK }}*
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ matrix.BUILD_CONFIGURATION }}_${{ env.PLATFORM }}.7z
        tag_name: ${{ steps.determine_version.outputs.version }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
